### ISSUE TITLE
키가 같아 죽는 문제가 발생

### ISSUE THREAD

**Issue by dalinaum** [dalinaum/m-issues#8]
키가 동일해 죽는 문제가 발생. id를 유니크하지 않게 내려주나?!

 ```
androidx.compose.foundation.lazy.LazyMeasuredItemProvider.getAndMeasure-ZjPyQlc(LazyMeasuredItemProvider.kt:47)
at androidx.compose.foundation.lazy.LazyListMeasureKt.measureLazyList-Hh3qtAg(LazyListMeasure.kt:164)
at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke-0kLqBqw(LazyList.kt:299)
at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(LazyList.kt:190)
at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$1$2$1.invoke-0kLqBqw(LazyLayout.kt:71)
at androidx.compose.foundation.lazy.layout.LazyLayoutKt$LazyLayout$1$2$1.invoke(LazyLayout.kt:69)
at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(SubcomposeLayout.kt:598)
at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(InnerNodeCoordinator.kt:103)
at androidx.compose.foundation.AndroidOverscrollKt$StretchOverscrollNonClippingLayer$2.invoke-3p2s80s(AndroidOverscroll.kt:578)
at androidx.compose.foundation.AndroidOverscrollKt$StretchOverscrollNonClippingLayer$2.invoke(AndroidOverscroll.kt:577)
at androidx.compose.ui.layout.LayoutModifierImpl.measure-3p2s80s(LayoutModifier.kt:294)
at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:155)
at androidx.compose.foundation.AndroidOverscrollKt$StretchOverscrollNonClippingLayer$1.invoke-3p2s80s(AndroidOverscroll.kt:562)
at androidx.compose.foundation.AndroidOverscrollKt$StretchOverscrollNonClippingLayer$1.invoke(AndroidOverscroll.kt:561)
at androidx.compose.ui.layout.LayoutModifierImpl.measure-3p2s80s(LayoutModifier.kt:294)
at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:155)
at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(GraphicsLayerModifier.kt:635)
at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(LayoutModifierNodeCoordinator.kt:155)
at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:1090)
at androidx.compose.ui.node.LayoutNodeLayoutDelegate$performMeasure$2.invoke(LayoutNodeLayoutDelegate.kt:1086)
at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2200)
at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:234)
at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:230)
at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:341)
at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:230)
at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:120)
at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:107)
at androidx.compose.ui.node.LayoutNodeLayoutDelegate.performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:1086)
at androidx.compose.ui.node.LayoutNodeLayoutDelegate.access$performMeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:36)
at androidx.compose.ui.node.LayoutNodeLayoutDelegate$MeasurePassDelegate.remeasure-BRTryo0(LayoutNodeLayoutDelegate.kt:342)
at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(LayoutNode.kt:1187)
at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release$default(LayoutNode.kt:1178)
at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(MeasureAndLayoutDelegate.kt:309)
at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:434)
at androidx.compose.ui.node.MeasureAndLayoutDelegate.access$remeasureAndRelayoutIfNeeded(MeasureAndLayoutDelegate.kt:39)
at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureAndLayout(MeasureAndLayoutDelegate.kt:330)
at androidx.compose.ui.platform.AndroidComposeView.measureAndLayout(AndroidComposeView.android.kt:805)
at androidx.compose.ui.node.Owner.measureAndLayout$default(Owner.kt:221)
at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1035)
at android.view.View.draw(View.java:22707)
at android.view.View.updateDisplayListIfDirty(View.java:21579)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
at android.view.View.updateDisplayListIfDirty(View.java:21535)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
at android.view.View.updateDisplayListIfDirty(View.java:21535)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
at android.view.View.updateDisplayListIfDirty(View.java:21535)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
at android.view.View.updateDisplayListIfDirty(View.java:21535)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:4525)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4245)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3374)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2179)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8787)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
at android.view.Choreographer.doCallbacks(Choreographer.java:845)
at android.view.Choreographer.doFrame(Choreographer.java:780)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7842)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by dalinaum** [comment]
```
2023-04-06 01:47:15.212 15979-15979 EEE                     io.github.dalinaum.m_issues          D  0 14052539 - lock-free
2023-04-06 01:47:15.212 15979-15979 EEE                     io.github.dalinaum.m_issues          D  1 25978881 - HeroForge-Anew
2023-04-06 01:47:15.212 15979-15979 EEE                     io.github.dalinaum.m_issues          D  2 99268865 - 2d-extras
2023-04-06 01:47:15.212 15979-15979 EEE                     io.github.dalinaum.m_issues          D  3 208301803 - FoundryVTT-BetterRolls5e
2023-04-06 01:47:15.212 15979-15979 EEE                     io.github.dalinaum.m_issues          D  4 60431775 - naturalcrit
2023-04-06 01:47:15.213 15979-15979 EEE                     io.github.dalinaum.m_issues          D  5 41257101 - DnD-battler
2023-04-06 01:47:15.213 15979-15979 EEE                     io.github.dalinaum.m_issues          D  6 88019260 - ESPMetric
2023-04-06 01:47:15.213 15979-15979 EEE                     io.github.dalinaum.m_issues          D  7 36841098 - mood
2023-04-06 01:47:15.213 15979-15979 EEE                     io.github.dalinaum.m_issues          D  8 13951377 - directx-d
2023-04-06 01:47:15.213 15979-15979 EEE                     io.github.dalinaum.m_issues          D  9 79802086 - BDSelf
2023-04-06 01:47:15.213 15979-15979 EEE                     io.github.dalinaum.m_issues          D  10 17130835 - Dispatcher
2023-04-06 01:47:15.213 15979-15979 EEE                     io.github.dalinaum.m_issues          D  11 137051507 - entangled
2023-04-06 01:47:15.214 15979-15979 EEE                     io.github.dalinaum.m_issues          D  12 1287514 - scid
2023-04-06 01:47:15.214 15979-15979 EEE                     io.github.dalinaum.m_issues          D  13 84231406 - suite01
2023-04-06 01:47:15.214 15979-15979 EEE                     io.github.dalinaum.m_issues          D  14 72478450 - course
2023-04-06 01:47:15.214 15979-15979 EEE                     io.github.dalinaum.m_issues          D  15 139731842 - fatturapa-testsdi
2023-04-06 01:47:15.214 15979-15979 EEE                     io.github.dalinaum.m_issues          D  16 132797317 - ircDDBGateway
2023-04-06 01:47:15.214 15979-15979 EEE                     io.github.dalinaum.m_issues          D  17 534370412 - GET3D
2023-04-06 01:47:15.214 15979-15979 EEE                     io.github.dalinaum.m_issues          D  18 45493905 - d3-force
2023-04-06 01:47:15.214 15979-15979 EEE                     io.github.dalinaum.m_issues          D  19 1367315 - mustache-d
2023-04-06 01:47:15.215 15979-15979 EEE                     io.github.dalinaum.m_issues          D  20 84666 - djbdns
2023-04-06 01:47:15.215 15979-15979 EEE                     io.github.dalinaum.m_issues          D  21 19175684 - HRCustomClasses
2023-04-06 01:47:15.215 15979-15979 EEE                     io.github.dalinaum.m_issues          D  22 20939247 - libddoc
2023-04-06 01:47:15.215 15979-15979 EEE                     io.github.dalinaum.m_issues          D  23 29422435 - vibe-aws
2023-04-06 01:47:15.215 15979-15979 EEE                     io.github.dalinaum.m_issues          D  24 1893266 - robotics-d-star-lite
2023-04-06 01:47:15.215 15979-15979 EEE                     io.github.dalinaum.m_issues          D  25 98861469 - brewdown
2023-04-06 01:47:15.215 15979-15979 EEE                     io.github.dalinaum.m_issues          D  26 21602406 - awesome-d
2023-04-06 01:47:15.215 15979-15979 EEE                     io.github.dalinaum.m_issues          D  27 1018571 - AsciiAsciiRevolution
2023-04-06 01:47:15.215 15979-15979 EEE                     io.github.dalinaum.m_issues          D  28 1215608 - jQuery-Feature-Carousel
2023-04-06 01:47:15.215 15979-15979 EEE                     io.github.dalinaum.m_issues          D  29 24427933 - dfix
```

```
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  0 2926434 - Mono-D
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  1 13852452 - dml
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  2 104899937 - docs
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  3 8352321 - BioD
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  4 134052854 - kanguen.github.io
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  5 61580555 - ClosedCube_SHT31D_Arduino
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  6 174449831 - docker-smartdns
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  7 8778644 - llvm-d
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  8 7593788 - go.dbus
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  9 111559409 - stdx-allocator
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  10 8889498 - dproto
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  11 7077608 - Dgame
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  12 156738230 - MYNT-EYE-D-SDK
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  13 177545876 - D
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  14 128897702 - site-eig
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  15 14052539 - lock-free
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  16 39267260 - paintown
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  17 25978881 - HeroForge-Anew
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  18 99268865 - 2d-extras
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  19 208301803 - FoundryVTT-BetterRolls5e
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  20 60431775 - naturalcrit
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  21 41257101 - DnD-battler
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  22 88019260 - ESPMetric
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  23 36841098 - mood
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  24 79802086 - BDSelf
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  25 17130835 - Dispatcher
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  26 137051507 - entangled
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  27 134697221 - semantic_slam
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  28 1287514 - scid
2023-04-06 01:47:10.505 15979-15979 EEE                     io.github.dalinaum.m_issues          D  29 13951377 - directx-d
2023-04-06 01:47:13.589 15979-15998 EGL_emulation           io.github.dalinaum.m_issues          D  app_time_stats: avg=103.73ms min=3.84ms max=2999.75ms count=34
2023-04-06 01:47:14.601 15979-15998 EGL_emulation           io.github.dalinaum.m_issues          D  app_time_stats: avg=33.69ms min=1.20ms max=552.98ms count=26
2023-04-06 01:47:15.212 15979-15979 EEE                     io.github.dalinaum.m_issues          D  0 14052539 - lock-free
2023-04-06 01:47:15.212 15979-15979 EEE                     io.github.dalinaum.m_issues          D  1 25978881 - HeroForge-Anew
2023-04-06 01:47:15.212 15979-15979 EEE                     io.github.dalinaum.m_issues          D  2 99268865 - 2d-extras
2023-04-06 01:47:15.212 15979-15979 EEE                     io.github.dalinaum.m_issues          D  3 208301803 - FoundryVTT-BetterRolls5e
2023-04-06 01:47:15.212 15979-15979 EEE                     io.github.dalinaum.m_issues          D  4 60431775 - naturalcrit
2023-04-06 01:47:15.213 15979-15979 EEE                     io.github.dalinaum.m_issues          D  5 41257101 - DnD-battler
2023-04-06 01:47:15.213 15979-15979 EEE                     io.github.dalinaum.m_issues          D  6 88019260 - ESPMetric
2023-04-06 01:47:15.213 15979-15979 EEE                     io.github.dalinaum.m_issues          D  7 36841098 - mood
2023-04-06 01:47:15.213 15979-15979 EEE                     io.github.dalinaum.m_issues          D  8 13951377 - directx-d
2023-04-06 01:47:15.213 15979-15979 EEE                     io.github.dalinaum.m_issues          D  9 79802086 - BDSelf
2023-04-06 01:47:15.213 15979-15979 EEE                     io.github.dalinaum.m_issues          D  10 17130835 - Dispatcher
2023-04-06 01:47:15.213 15979-15979 EEE                     io.github.dalinaum.m_issues          D  11 137051507 - entangled
2023-04-06 01:47:15.214 15979-15979 EEE                     io.github.dalinaum.m_issues          D  12 1287514 - scid
2023-04-06 01:47:15.214 15979-15979 EEE                     io.github.dalinaum.m_issues          D  13 84231406 - suite01
2023-04-06 01:47:15.214 15979-15979 EEE                     io.github.dalinaum.m_issues          D  14 72478450 - course
2023-04-06 01:47:15.214 15979-15979 EEE                     io.github.dalinaum.m_issues          D  15 139731842 - fatturapa-testsdi
2023-04-06 01:47:15.214 15979-15979 EEE                     io.github.dalinaum.m_issues          D  16 132797317 - ircDDBGateway
2023-04-06 01:47:15.214 15979-15979 EEE                     io.github.dalinaum.m_issues          D  17 534370412 - GET3D
2023-04-06 01:47:15.214 15979-15979 EEE                     io.github.dalinaum.m_issues          D  18 45493905 - d3-force
2023-04-06 01:47:15.214 15979-15979 EEE                     io.github.dalinaum.m_issues          D  19 1367315 - mustache-d
2023-04-06 01:47:15.215 15979-15979 EEE                     io.github.dalinaum.m_issues          D  20 84666 - djbdns
2023-04-06 01:47:15.215 15979-15979 EEE                     io.github.dalinaum.m_issues          D  21 19175684 - HRCustomClasses
2023-04-06 01:47:15.215 15979-15979 EEE                     io.github.dalinaum.m_issues          D  22 20939247 - libddoc
2023-04-06 01:47:15.215 15979-15979 EEE                     io.github.dalinaum.m_issues          D  23 29422435 - vibe-aws
2023-04-06 01:47:15.215 15979-15979 EEE                     io.github.dalinaum.m_issues          D  24 1893266 - robotics-d-star-lite
2023-04-06 01:47:15.215 15979-15979 EEE                     io.github.dalinaum.m_issues          D  25 98861469 - brewdown
2023-04-06 01:47:15.215 15979-15979 EEE                     io.github.dalinaum.m_issues          D  26 21602406 - awesome-d
2023-04-06 01:47:15.215 15979-15979 EEE                     io.github.dalinaum.m_issues          D  27 1018571 - AsciiAsciiRevolution
2023-04-06 01:47:15.215 15979-15979 EEE                     io.github.dalinaum.m_issues          D  28 1215608 - jQuery-Feature-Carousel
2023-04-06 01:47:15.215 15979-15979 EEE                     io.github.dalinaum.m_issues          D  29 24427933 - dfix
```

실제로 같은 값이 오는 듯 (....)
